"""new tables

Revision ID: 476ebc3e37eb
Revises: 
Create Date: 2026-04-27 16:58:11.947840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476ebc3e37eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.DateTime(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=28), nullable=False),
    sa.Column('map', sa.String(length=28), nullable=False),
    sa.Column('rr_change', sa.Integer(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('my_team_score', sa.Integer(), nullable=False),
    sa.Column('enemy_team_score', sa.Integer(), nullable=False),
    sa.Column('rank_after', sa.String(length=28), nullable=False),
    sa.Column('rank_before', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_assists'), ['assists'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_deaths'), ['deaths'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_enemy_team_score'), ['enemy_team_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_kills'), ['kills'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_map'), ['map'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_my_team_score'), ['my_team_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_rank_after'), ['rank_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_rank_before'), ['rank_before'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_rr_change'), ['rr_change'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_rr_change'))
        batch_op.drop_index(batch_op.f('ix_match_rank_before'))
        batch_op.drop_index(batch_op.f('ix_match_rank_after'))
        batch_op.drop_index(batch_op.f('ix_match_my_team_score'))
        batch_op.drop_index(batch_op.f('ix_match_map'))
        batch_op.drop_index(batch_op.f('ix_match_kills'))
        batch_op.drop_index(batch_op.f('ix_match_enemy_team_score'))
        batch_op.drop_index(batch_op.f('ix_match_deaths'))
        batch_op.drop_index(batch_op.f('ix_match_assists'))
        batch_op.drop_index(batch_op.f('ix_match_agent'))

    op.drop_table('match')
    # ### end Alembic commands ###
